/**:
  ros__parameters:
    out_of_lane:
      method: "threshold"  # [-] threshold or TTC
      distance_threshold: 5.0  # [m] minimum distance
      overlap_min_distance: 0.0  # [m] minimum distance inside a lanelet to for an overlap to be considered
      ego:
        extra_front_offset: 3.0 # [m] extra front distance
        extra_rear_offset: 0.0 # [m] extra rear distance
        extra_right_offset: 0.0 # [m] extra right distance
        extra_left_offset: 0.0 # [m] extra left distance