/**:
  ros__parameters:

    # -- system --
    ctrl_period: 0.03               # control period [s]
    traj_resample_dist: 0.1         # path resampling interval [m]
    use_steer_prediction: false     # flag for using steer prediction (do not use steer measurement)
    admissible_position_error: 5.0  # stop mpc calculation when error is larger than the following value
    admissible_yaw_error_rad: 1.57  # stop mpc calculation when error is larger than the following value

    # -- path smoothing --
    enable_path_smoothing: false   # flag for path smoothing
    path_filter_moving_ave_num: 25 # param of moving average filter for path smoothing
    curvature_smoothing_num_traj: 15        # point-to-point index distance used in curvature calculation (for trajectory): curvature is calculated from three points p(i-num), p(i), p(i+num)
    curvature_smoothing_num_ref_steer: 15   # point-to-point index distance used in curvature calculation (for steer command reference): curvature is calculated from three points p(i-num), p(i), p(i+num)

    # -- mpc optimization --
    qp_solver_type: "osqp"                       # optimization solver option (unconstraint_fast or osqp)
    mpc_prediction_horizon: 50                   # prediction horizon step
    mpc_prediction_dt: 0.1                       # prediction horizon period [s]

    # -- vehicle model --
    vehicle_model_type: "kinematics" # vehicle model type for mpc prediction. option is kinematics, kinematics_no_delay, and dynamics
    vehicle_model_steer_tau: 0.3     # steering dynamics time constant (1d approximation) [s]
    steer_lim_deg: 40.0              # steering angle limit [deg]
    steer_rate_lim_dps: 600.0        # steering angle rate limit [deg/s]
    acceleration_limit: 2.0          # acceleration limit for trajectory velocity modification [m/ss]
    velocity_time_constant: 0.3      # velocity dynamics time constant  for trajectory velocity modification [s]

    # stop state: steering command is kept in the previous value in the stop state.
    stop_state_entry_ego_speed: 0.001
    stop_state_entry_target_speed: 0.001
