/**:
  ros__parameters:
    control_rate: 30.0

    enable_smooth_stop: true
    enable_overshoot_emergency: true
    enable_slope_compensation: false

    # state transition
    drive_state_stop_dist: 0.5
    drive_state_offset_stop_dist: 1.0
    stopping_state_stop_dist: 0.49
    stopped_state_entry_duration_time: 0.1
    stopped_state_entry_vel: 0.1
    stopped_state_entry_acc: 0.1
    emergency_state_overshoot_stop_dist: 1.5
    emergency_state_traj_trans_dev: 3.0
    emergency_state_traj_rot_dev: 0.7

    # drive state
    enable_brake_keeping_before_stop: false

    # stopped state
    stopped_vel: 0.0
    stopped_acc: -3.4
    stopped_jerk: -5.0

    # emergency state
    emergency_vel: 0.0
    emergency_acc: -5.0
    emergency_jerk: -3.0

    # acceleration limit
    max_acc: 3.0
    min_acc: -5.0

    # jerk limit
    max_jerk: 2.0
    min_jerk: -5.0

    # pitch
    use_trajectory_for_pitch_calculation: false
    max_pitch_rad: 0.1
    min_pitch_rad: -0.1
