/**:
  ros__parameters:
    common:
      # output
      output_delta_arc_length: 0.5     #  delta arc length for output trajectory [m]
      output_backward_traj_length: 5.0  # backward length for backward trajectory from base_link [m]

    debug:
      # flag to show
      enable_calculation_time_info: false
      id: 0  # id of the candidate paths for which to print/show details (e.g., footprint in rviz)

    preprocessing:
      force_zero_initial_deviation: True  # if true, initial planning starts from the reference path
      force_zero_initial_heading: True # if true, initial planning starts with a heading aligned with the reference path
      smooth_reference_trajectory: False # if true, the reference trajectory is smoothed before being used for planning
    constraints:
      hard:
        max_curvature: 0.2
        min_curvature: -0.2
      soft:
        lateral_deviation_weight: 0.1
        length_weight: 1.0
        curvature_weight: 1.0
    sampling:
      enable_frenet: True
      enable_bezier: True
      resolution: 0.5
      previous_path_reuse_points_nb: 2  # number of points reused from the previously generated path (0:no reuse, 1:replan from end of prev path, 2: end and mid of prev path, etc)
      target_lengths: [10.0, 20.0]
      frenet:
        target_lateral_positions: [-0.5, 0.0, 0.5]
        target_lateral_velocities: [-0.1, 0.0, 0.1]
        target_lateral_accelerations: [0.0]
      bezier:
        nb_k: 3
        mk_min: 0.0
        mk_max: 10.0
        nb_t: 5
        mt_min: 0.3
        mt_max: 1.7
