launch:
  # controler modules
  - arg:
      name: trajectory_follower_mode
      default: "trajectory_follower_node"
      # option: smart_mpc_trajectory_follower
      #         none
  - arg:
      name: lateral_controller_mode
      default: "mpc"
  - arg:
      name: longitudinal_controller_mode
      default: "pid"

  # modules changeable for debugging/testing only
  - arg:
      name: launch_trajectory_follower_components
      default: "true"
  - arg:
      name: launch_external_cmd_selector
      default: "true"
  - arg:
      name: launch_external_cmd_converter
      default: "true"
  - arg:
      name: launch_control_validator
      default: "true"
  - arg:
      name: launch_control_evaluator
      default: "true"

  # optional modules
  - arg:
      name: launch_obstacle_collision_checker
      default: "false"
  - arg:
      name: launch_autonomous_emergency_braking
      default: "true"
  - arg:
      name: launch_predicted_path_checker
      default: "false"
  - arg:
      name: launch_collision_detector
      default: "false"
