/**:
  ros__parameters:
    localization:
      type: diagnostic_aggregator/AnalyzerGroup
      path: localization
      analyzers:
        node_alive_monitoring:
          type: diagnostic_aggregator/AnalyzerGroup
          path: node_alive_monitoring
          analyzers:
            topic_status:
              type: diagnostic_aggregator/GenericAnalyzer
              path: topic_status
              contains: [": localization_topic_status"]
              timeout: 1.0

        eagleye:
          type: diagnostic_aggregator/AnalyzerGroup
          path: eagleye
          analyzers:
            twist:
              type: diagnostic_aggregator/GenericAnalyzer
              path: twist
              contains: [": eagleye_twist"]
              timeout: 3.0

            localization_accuracy:
              type: diagnostic_aggregator/GenericAnalyzer
              path: localization_accuracy
              contains: [": localization_accuracy"]
              timeout: 1.0
