/**:
  ros__parameters:
    lanelet2_map_projector_type: UTM   # Options: MGRS, UTM, local
    latitude: 32.53284662620757        # Latitude of map_origin, using in UTM
    longitude: -112.06487986420538          # Longitude of map_origin, using in UTM

    center_line_resolution: 5.0         # [m]
